name: CI

on:
  push:
    branches:
      - main

jobs:
  run-npm-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.10.5
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'npm'

      - run: npm install
      - run: npm run-script types
      - run: npm run-script lint
